/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
    const collection = new Collection({
                                          "createRule": null,
                                          "deleteRule": null,
                                          "fields": [
                                              {
                                                  "autogeneratePattern": "",
                                                  "hidden": false,
                                                  "id": "text3208210256",
                                                  "max": 0,
                                                  "min": 0,
                                                  "name": "id",
                                                  "pattern": "^[a-z0-9]+$",
                                                  "presentable": false,
                                                  "primaryKey": true,
                                                  "required": true,
                                                  "system": true,
                                                  "type": "text",
                                              },
                                              {
                                                  "cascadeDelete": false,
                                                  "collectionId": "cflmwtgulbeuubc",
                                                  "hidden": false,
                                                  "id": "relation2301795621",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "resource_id",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_x3if",
                                                  "name": "resource_created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_v1Zx",
                                                  "name": "resource_updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_BCYa",
                                                  "max": null,
                                                  "min": 1,
                                                  "name": "order_index",
                                                  "onlyInt": false,
                                                  "presentable": false,
                                                  "required": true,
                                                  "system": false,
                                                  "type": "number",
                                              },
                                              {
                                                  "cascadeDelete": false,
                                                  "collectionId": "b36lt0a0v5anqh3",
                                                  "hidden": false,
                                                  "id": "relation3455582614",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "lesson_id",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "autogeneratePattern": "",
                                                  "hidden": false,
                                                  "id": "_clone_p24F",
                                                  "max": 0,
                                                  "min": 0,
                                                  "name": "lesson_title",
                                                  "pattern": "",
                                                  "presentable": false,
                                                  "primaryKey": false,
                                                  "required": true,
                                                  "system": false,
                                                  "type": "text",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_dpYI",
                                                  "name": "lesson_created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_KQVU",
                                                  "name": "lesson_updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "cascadeDelete": true,
                                                  "collectionId": "7jo5p6lzwwht0s5",
                                                  "hidden": false,
                                                  "id": "_clone_xqiF",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "lesson_course",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_IimF",
                                                  "name": "created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_ZCBo",
                                                  "name": "updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                          ],
                                          "id": "pbc_3204733176",
                                          "indexes": [],
                                          "listRule": "@request.auth.id != \"\" && lesson_course.assignees.id ?= @request.auth.id",
                                          "name": "lesson_resources_view",
                                          "system": false,
                                          "type": "view",
                                          "updateRule": null,
                                          "viewQuery": "SELECT \n    (ROW_NUMBER() OVER()) as id,\n    lr.id            AS resource_id,\n    lr.created       AS resource_created,\n    lr.updated       AS resource_updated,\n    lrl.order_index  AS order_index,\n    l.id             AS lesson_id,\n    l.title          AS lesson_title,\n    l.created        AS lesson_created,\n    l.updated        AS lesson_updated,\n    l.course         AS lesson_course,\n    lrl.created      AS created,\n    lrl.updated      AS updated\nFROM lesson_resources lr\nJOIN lesson_resources_lessons lrl ON lr.id = lrl.lesson_resource\nJOIN lessons l ON l.id = lrl.lesson;",
                                          "viewRule": "@request.auth.id != \"\" && lesson_course.assignees.id ?= @request.auth.id",
                                      });

    return app.save(collection);
}, (app) => {
    const collection = app.findCollectionByNameOrId("pbc_3204733176");

    return app.delete(collection);
});
