/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
    const collection = new Collection({
                                          "createRule": null,
                                          "deleteRule": null,
                                          "fields": [
                                              {
                                                  "autogeneratePattern": "",
                                                  "hidden": false,
                                                  "id": "text3208210256",
                                                  "max": 0,
                                                  "min": 0,
                                                  "name": "id",
                                                  "pattern": "^[a-z0-9]+$",
                                                  "presentable": false,
                                                  "primaryKey": true,
                                                  "required": true,
                                                  "system": true,
                                                  "type": "text",
                                              },
                                              {
                                                  "cascadeDelete": false,
                                                  "collectionId": "yaoytodp8g23zu3",
                                                  "hidden": false,
                                                  "id": "relation2176764098",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "faq_id",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_pIHL",
                                                  "name": "faq_created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_e20K",
                                                  "name": "faq_updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_7TXj",
                                                  "max": null,
                                                  "min": 1,
                                                  "name": "order_index",
                                                  "onlyInt": false,
                                                  "presentable": false,
                                                  "required": true,
                                                  "system": false,
                                                  "type": "number",
                                              },
                                              {
                                                  "cascadeDelete": false,
                                                  "collectionId": "b36lt0a0v5anqh3",
                                                  "hidden": false,
                                                  "id": "relation3455582614",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "lesson_id",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "autogeneratePattern": "",
                                                  "hidden": false,
                                                  "id": "_clone_By7k",
                                                  "max": 0,
                                                  "min": 0,
                                                  "name": "lesson_title",
                                                  "pattern": "",
                                                  "presentable": false,
                                                  "primaryKey": false,
                                                  "required": true,
                                                  "system": false,
                                                  "type": "text",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_S13P",
                                                  "name": "lesson_created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_NiPt",
                                                  "name": "lesson_updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "cascadeDelete": true,
                                                  "collectionId": "7jo5p6lzwwht0s5",
                                                  "hidden": false,
                                                  "id": "_clone_XZOf",
                                                  "maxSelect": 1,
                                                  "minSelect": 0,
                                                  "name": "lesson_course",
                                                  "presentable": false,
                                                  "required": false,
                                                  "system": false,
                                                  "type": "relation",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_wvhR",
                                                  "name": "created",
                                                  "onCreate": true,
                                                  "onUpdate": false,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                              {
                                                  "hidden": false,
                                                  "id": "_clone_Npip",
                                                  "name": "updated",
                                                  "onCreate": true,
                                                  "onUpdate": true,
                                                  "presentable": false,
                                                  "system": false,
                                                  "type": "autodate",
                                              },
                                          ],
                                          "id": "pbc_1226187020",
                                          "indexes": [],
                                          "listRule": "@request.auth.id != \"\" && lesson_course.assignees.id ?= @request.auth.id",
                                          "name": "lesson_faqs_view",
                                          "system": false,
                                          "type": "view",
                                          "updateRule": null,
                                          "viewQuery": "SELECT \n    (ROW_NUMBER() OVER()) as id,\n    lf.id            AS faq_id,\n    lf.created       AS faq_created,\n    lf.updated       AS faq_updated,\n    lfl.order_index  AS order_index,\n    l.id             AS lesson_id,\n    l.title          AS lesson_title,\n    l.created        AS lesson_created,\n    l.updated        AS lesson_updated,\n    l.course         AS lesson_course,\n    lfl.created      AS created,\n    lfl.updated      AS updated\nFROM lesson_faqs lf\nJOIN lesson_faqs_lessons lfl ON lf.id = lfl.lesson_faq\nJOIN lessons l ON l.id = lfl.lesson;",
                                          "viewRule": "@request.auth.id != \"\" && lesson_course.assignees.id ?= @request.auth.id",
                                      });

    return app.save(collection);
}, (app) => {
    const collection = app.findCollectionByNameOrId("pbc_1226187020");

    return app.delete(collection);
});
