/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
    const EffectScope: typeof import("vue").EffectScope;
    const acceptHMRUpdate: typeof import("pinia").acceptHMRUpdate;
    const cleanFileName: typeof import("./src/lib/utils").cleanFileName;
    const computed: typeof import("vue").computed;
    const createApp: typeof import("vue").createApp;
    const createPinia: typeof import("pinia").createPinia;
    const customRef: typeof import("vue").customRef;
    const defineAsyncComponent: typeof import("vue").defineAsyncComponent;
    const defineComponent: typeof import("vue").defineComponent;
    const definePage: typeof import("vue-router/experimental").definePage;
    const defineStore: typeof import("pinia").defineStore;
    const detectLocale: typeof import("./src/lib/locale").detectLocale;
    const effectScope: typeof import("vue").effectScope;
    const fetchCourses: typeof import("./src/lib/useFetchRecords").fetchCourses;
    const fetchLessonFaqs: typeof import("./src/lib/useFetchRecords").fetchLessonFaqs;
    const fetchLessonResources: typeof import("./src/lib/useFetchRecords").fetchLessonResources;
    const fetchLessons: typeof import("./src/lib/useFetchRecords").fetchLessons;
    const fetchProgress: typeof import("./src/lib/useFetchRecords").fetchProgress;
    const fetchResources: typeof import("./src/lib/useFetchRecords").fetchResources;
    const getActivePinia: typeof import("pinia").getActivePinia;
    const getCurrentInstance: typeof import("vue").getCurrentInstance;
    const getCurrentScope: typeof import("vue").getCurrentScope;
    const getCurrentWatcher: typeof import("vue").getCurrentWatcher;
    const getGoogleDriveFileId: typeof import("./src/lib/utils").getGoogleDriveFileId;
    const getYouTubeVideoId: typeof import("./src/lib/utils").getYouTubeVideoId;
    const h: typeof import("vue").h;
    const inject: typeof import("vue").inject;
    const isGoogleDriveUrl: typeof import("./src/lib/utils").isGoogleDriveUrl;
    const isProxy: typeof import("vue").isProxy;
    const isReactive: typeof import("vue").isReactive;
    const isReadonly: typeof import("vue").isReadonly;
    const isRef: typeof import("vue").isRef;
    const isShallow: typeof import("vue").isShallow;
    const mapActions: typeof import("pinia").mapActions;
    const mapGetters: typeof import("pinia").mapGetters;
    const mapState: typeof import("pinia").mapState;
    const mapStores: typeof import("pinia").mapStores;
    const mapWritableState: typeof import("pinia").mapWritableState;
    const markRaw: typeof import("vue").markRaw;
    const nextTick: typeof import("vue").nextTick;
    const onActivated: typeof import("vue").onActivated;
    const onBeforeMount: typeof import("vue").onBeforeMount;
    const onBeforeRouteLeave: typeof import("vue-router").onBeforeRouteLeave;
    const onBeforeRouteUpdate: typeof import("vue-router").onBeforeRouteUpdate;
    const onBeforeUnmount: typeof import("vue").onBeforeUnmount;
    const onBeforeUpdate: typeof import("vue").onBeforeUpdate;
    const onDeactivated: typeof import("vue").onDeactivated;
    const onErrorCaptured: typeof import("vue").onErrorCaptured;
    const onMounted: typeof import("vue").onMounted;
    const onRenderTracked: typeof import("vue").onRenderTracked;
    const onRenderTriggered: typeof import("vue").onRenderTriggered;
    const onScopeDispose: typeof import("vue").onScopeDispose;
    const onServerPrefetch: typeof import("vue").onServerPrefetch;
    const onUnmounted: typeof import("vue").onUnmounted;
    const onUpdated: typeof import("vue").onUpdated;
    const onWatcherCleanup: typeof import("vue").onWatcherCleanup;
    const pb: typeof import("./src/lib/pocketbase").pb;
    const provide: typeof import("vue").provide;
    const reactive: typeof import("vue").reactive;
    const readonly: typeof import("vue").readonly;
    const ref: typeof import("vue").ref;
    const resolveComponent: typeof import("vue").resolveComponent;
    const sanitizeHTML: typeof import("./src/lib/utils").sanitizeHTML;
    const scrollToCourse: typeof import("./src/lib/utils").scrollToCourse;
    const setActivePinia: typeof import("pinia").setActivePinia;
    const setMapStoreSuffix: typeof import("pinia").setMapStoreSuffix;
    const shallowReactive: typeof import("vue").shallowReactive;
    const shallowReadonly: typeof import("vue").shallowReadonly;
    const shallowRef: typeof import("vue").shallowRef;
    const slugifyId: typeof import("./src/lib/utils").slugifyId;
    const storeToRefs: typeof import("pinia").storeToRefs;
    const toRaw: typeof import("vue").toRaw;
    const toRef: typeof import("vue").toRef;
    const toRefs: typeof import("vue").toRefs;
    const toValue: typeof import("vue").toValue;
    const triggerRef: typeof import("vue").triggerRef;
    const unref: typeof import("vue").unref;
    const updateProgressStatus: typeof import("./src/lib/utils").updateProgressStatus;
    const useAlertStore: typeof import("./src/stores/useAlertStore").useAlertStore;
    const useAttrs: typeof import("vue").useAttrs;
    const useAuthStore: typeof import("./src/stores/useAuthStore").useAuthStore;
    const useCoursesStore: typeof import("./src/stores/useCoursesStore").useCoursesStore;
    const useCssModule: typeof import("vue").useCssModule;
    const useCssVars: typeof import("vue").useCssVars;
    const useCustomSettingsStore: typeof import("./src/stores/useCustomSettingsStore").useCustomSettingsStore;
    const useCustomizeJson: typeof import("./src/lib/useCustomizeJson").default;
    const useFetchRecords: typeof import("./src/lib/useFetchRecords").useFetchRecords;
    const useHead: typeof import("@vueuse/head").useHead;
    const useI18n: typeof import("vue-i18n").useI18n;
    const useId: typeof import("vue").useId;
    const useLessonFaqsStore: typeof import("./src/stores/useLessonFaqsStore").useLessonFaqsStore;
    const useLessonResourcesStore: typeof import("./src/stores/useLessonResourcesStore").useLessonResourcesStore;
    const useLessonsByCourseStore: typeof import("./src/stores/useLessonsByCourseStore").useLessonsByCourseStore;
    const useLessonsStore: typeof import("./src/stores/useLessonsStore").useLessonsStore;
    const useLocaleStore: typeof import("./src/stores/useLocaleStore").useLocaleStore;
    const useModel: typeof import("vue").useModel;
    const useProgressStore: typeof import("./src/stores/useProgressStore").useProgressStore;
    const useResourcesStore: typeof import("./src/stores/useResourcesStore").useResourcesStore;
    const useRoute: typeof import("vue-router").useRoute;
    const useRouter: typeof import("vue-router").useRouter;
    const useSeoMeta: typeof import("@vueuse/head").useSeoMeta;
    const useSlots: typeof import("vue").useSlots;
    const useTemplateRef: typeof import("vue").useTemplateRef;
    const useUIStore: typeof import("./src/stores/useUIStore").useUIStore;
    const watch: typeof import("vue").watch;
    const watchEffect: typeof import("vue").watchEffect;
    const watchPostEffect: typeof import("vue").watchPostEffect;
    const watchSyncEffect: typeof import("vue").watchSyncEffect;
}
// for type re-export
declare global {
    // @ts-ignore
    export type {
        Component,
        Slot,
        Slots,
        ComponentPublicInstance,
        ComputedRef,
        DirectiveBinding,
        ExtractDefaultPropTypes,
        ExtractPropTypes,
        ExtractPublicPropTypes,
        InjectionKey,
        PropType,
        Ref,
        ShallowRef,
        MaybeRef,
        MaybeRefOrGetter,
        VNode,
        WritableComputedRef,
    } from "vue";
    import("vue");
    // @ts-ignore
    export type {
        User,
        Course,
        LessonFaq,
        LessonResource,
        Lesson,
        Status,
        Progress,
        Resource,
        Users,
        Courses,
        LessonFaqs,
        LessonResources,
        Lessons,
        Resources,
    } from "./src/types/collections.d";
    import("./src/types/collections.d");
    // @ts-ignore
    export type { Locales } from "./src/types/locales.d";
    import("./src/types/locales.d");
}

// for vue template auto import
import { UnwrapRef } from "vue";

declare module "vue" {
    interface GlobalComponents {
    }

    interface ComponentCustomProperties {
        readonly EffectScope: UnwrapRef<typeof import("vue")["EffectScope"]>;
        readonly acceptHMRUpdate: UnwrapRef<typeof import("pinia")["acceptHMRUpdate"]>;
        readonly cleanFileName: UnwrapRef<typeof import("./src/lib/utils")["cleanFileName"]>;
        readonly computed: UnwrapRef<typeof import("vue")["computed"]>;
        readonly createApp: UnwrapRef<typeof import("vue")["createApp"]>;
        readonly createPinia: UnwrapRef<typeof import("pinia")["createPinia"]>;
        readonly customRef: UnwrapRef<typeof import("vue")["customRef"]>;
        readonly defineAsyncComponent: UnwrapRef<typeof import("vue")["defineAsyncComponent"]>;
        readonly defineComponent: UnwrapRef<typeof import("vue")["defineComponent"]>;
        readonly definePage: UnwrapRef<typeof import("vue-router/experimental")["definePage"]>;
        readonly defineStore: UnwrapRef<typeof import("pinia")["defineStore"]>;
        readonly detectLocale: UnwrapRef<typeof import("./src/lib/locale")["detectLocale"]>;
        readonly effectScope: UnwrapRef<typeof import("vue")["effectScope"]>;
        readonly fetchCourses: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchCourses"]>;
        readonly fetchLessonFaqs: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchLessonFaqs"]>;
        readonly fetchLessonResources: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchLessonResources"]>;
        readonly fetchLessons: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchLessons"]>;
        readonly fetchProgress: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchProgress"]>;
        readonly fetchResources: UnwrapRef<typeof import("./src/lib/useFetchRecords")["fetchResources"]>;
        readonly getActivePinia: UnwrapRef<typeof import("pinia")["getActivePinia"]>;
        readonly getCurrentInstance: UnwrapRef<typeof import("vue")["getCurrentInstance"]>;
        readonly getCurrentScope: UnwrapRef<typeof import("vue")["getCurrentScope"]>;
        readonly getCurrentWatcher: UnwrapRef<typeof import("vue")["getCurrentWatcher"]>;
        readonly getGoogleDriveFileId: UnwrapRef<typeof import("./src/lib/utils")["getGoogleDriveFileId"]>;
        readonly getYouTubeVideoId: UnwrapRef<typeof import("./src/lib/utils")["getYouTubeVideoId"]>;
        readonly h: UnwrapRef<typeof import("vue")["h"]>;
        readonly inject: UnwrapRef<typeof import("vue")["inject"]>;
        readonly isGoogleDriveUrl: UnwrapRef<typeof import("./src/lib/utils")["isGoogleDriveUrl"]>;
        readonly isProxy: UnwrapRef<typeof import("vue")["isProxy"]>;
        readonly isReactive: UnwrapRef<typeof import("vue")["isReactive"]>;
        readonly isReadonly: UnwrapRef<typeof import("vue")["isReadonly"]>;
        readonly isRef: UnwrapRef<typeof import("vue")["isRef"]>;
        readonly isShallow: UnwrapRef<typeof import("vue")["isShallow"]>;
        readonly mapActions: UnwrapRef<typeof import("pinia")["mapActions"]>;
        readonly mapGetters: UnwrapRef<typeof import("pinia")["mapGetters"]>;
        readonly mapState: UnwrapRef<typeof import("pinia")["mapState"]>;
        readonly mapStores: UnwrapRef<typeof import("pinia")["mapStores"]>;
        readonly mapWritableState: UnwrapRef<typeof import("pinia")["mapWritableState"]>;
        readonly markRaw: UnwrapRef<typeof import("vue")["markRaw"]>;
        readonly nextTick: UnwrapRef<typeof import("vue")["nextTick"]>;
        readonly onActivated: UnwrapRef<typeof import("vue")["onActivated"]>;
        readonly onBeforeMount: UnwrapRef<typeof import("vue")["onBeforeMount"]>;
        readonly onBeforeRouteLeave: UnwrapRef<typeof import("vue-router")["onBeforeRouteLeave"]>;
        readonly onBeforeRouteUpdate: UnwrapRef<typeof import("vue-router")["onBeforeRouteUpdate"]>;
        readonly onBeforeUnmount: UnwrapRef<typeof import("vue")["onBeforeUnmount"]>;
        readonly onBeforeUpdate: UnwrapRef<typeof import("vue")["onBeforeUpdate"]>;
        readonly onDeactivated: UnwrapRef<typeof import("vue")["onDeactivated"]>;
        readonly onErrorCaptured: UnwrapRef<typeof import("vue")["onErrorCaptured"]>;
        readonly onMounted: UnwrapRef<typeof import("vue")["onMounted"]>;
        readonly onRenderTracked: UnwrapRef<typeof import("vue")["onRenderTracked"]>;
        readonly onRenderTriggered: UnwrapRef<typeof import("vue")["onRenderTriggered"]>;
        readonly onScopeDispose: UnwrapRef<typeof import("vue")["onScopeDispose"]>;
        readonly onServerPrefetch: UnwrapRef<typeof import("vue")["onServerPrefetch"]>;
        readonly onUnmounted: UnwrapRef<typeof import("vue")["onUnmounted"]>;
        readonly onUpdated: UnwrapRef<typeof import("vue")["onUpdated"]>;
        readonly onWatcherCleanup: UnwrapRef<typeof import("vue")["onWatcherCleanup"]>;
        readonly pb: UnwrapRef<typeof import("./src/lib/pocketbase")["pb"]>;
        readonly provide: UnwrapRef<typeof import("vue")["provide"]>;
        readonly reactive: UnwrapRef<typeof import("vue")["reactive"]>;
        readonly readonly: UnwrapRef<typeof import("vue")["readonly"]>;
        readonly ref: UnwrapRef<typeof import("vue")["ref"]>;
        readonly resolveComponent: UnwrapRef<typeof import("vue")["resolveComponent"]>;
        readonly sanitizeHTML: UnwrapRef<typeof import("./src/lib/utils")["sanitizeHTML"]>;
        readonly scrollToCourse: UnwrapRef<typeof import("./src/lib/utils")["scrollToCourse"]>;
        readonly setActivePinia: UnwrapRef<typeof import("pinia")["setActivePinia"]>;
        readonly setMapStoreSuffix: UnwrapRef<typeof import("pinia")["setMapStoreSuffix"]>;
        readonly shallowReactive: UnwrapRef<typeof import("vue")["shallowReactive"]>;
        readonly shallowReadonly: UnwrapRef<typeof import("vue")["shallowReadonly"]>;
        readonly shallowRef: UnwrapRef<typeof import("vue")["shallowRef"]>;
        readonly slugifyId: UnwrapRef<typeof import("./src/lib/utils")["slugifyId"]>;
        readonly storeToRefs: UnwrapRef<typeof import("pinia")["storeToRefs"]>;
        readonly toRaw: UnwrapRef<typeof import("vue")["toRaw"]>;
        readonly toRef: UnwrapRef<typeof import("vue")["toRef"]>;
        readonly toRefs: UnwrapRef<typeof import("vue")["toRefs"]>;
        readonly toValue: UnwrapRef<typeof import("vue")["toValue"]>;
        readonly triggerRef: UnwrapRef<typeof import("vue")["triggerRef"]>;
        readonly unref: UnwrapRef<typeof import("vue")["unref"]>;
        readonly updateProgressStatus: UnwrapRef<typeof import("./src/lib/utils")["updateProgressStatus"]>;
        readonly useAttrs: UnwrapRef<typeof import("vue")["useAttrs"]>;
        readonly useAuthStore: UnwrapRef<typeof import("./src/stores/useAuthStore")["useAuthStore"]>;
        readonly useCoursesStore: UnwrapRef<typeof import("./src/stores/useCoursesStore")["useCoursesStore"]>;
        readonly useCssModule: UnwrapRef<typeof import("vue")["useCssModule"]>;
        readonly useCssVars: UnwrapRef<typeof import("vue")["useCssVars"]>;
        readonly useCustomSettingsStore: UnwrapRef<typeof import("./src/stores/useCustomSettingsStore")["useCustomSettingsStore"]>;
        readonly useCustomizeJson: UnwrapRef<typeof import("./src/lib/useCustomizeJson")["default"]>;
        readonly useFetchRecords: UnwrapRef<typeof import("./src/lib/useFetchRecords")["useFetchRecords"]>;
        readonly useHead: UnwrapRef<typeof import("@vueuse/head")["useHead"]>;
        readonly useI18n: UnwrapRef<typeof import("vue-i18n")["useI18n"]>;
        readonly useId: UnwrapRef<typeof import("vue")["useId"]>;
        readonly useLessonFaqsStore: UnwrapRef<typeof import("./src/stores/useLessonFaqsStore")["useLessonFaqsStore"]>;
        readonly useLessonResourcesStore: UnwrapRef<typeof import("./src/stores/useLessonResourcesStore")["useLessonResourcesStore"]>;
        readonly useLessonsByCourseStore: UnwrapRef<typeof import("./src/stores/useLessonsByCourseStore")["useLessonsByCourseStore"]>;
        readonly useLessonsStore: UnwrapRef<typeof import("./src/stores/useLessonsStore")["useLessonsStore"]>;
        readonly useLocaleStore: UnwrapRef<typeof import("./src/stores/useLocaleStore")["useLocaleStore"]>;
        readonly useModel: UnwrapRef<typeof import("vue")["useModel"]>;
        readonly useProgressStore: UnwrapRef<typeof import("./src/stores/useProgressStore")["useProgressStore"]>;
        readonly useResourcesStore: UnwrapRef<typeof import("./src/stores/useResourcesStore")["useResourcesStore"]>;
        readonly useRoute: UnwrapRef<typeof import("vue-router")["useRoute"]>;
        readonly useRouter: UnwrapRef<typeof import("vue-router")["useRouter"]>;
        readonly useSeoMeta: UnwrapRef<typeof import("@vueuse/head")["useSeoMeta"]>;
        readonly useSlots: UnwrapRef<typeof import("vue")["useSlots"]>;
        readonly useTemplateRef: UnwrapRef<typeof import("vue")["useTemplateRef"]>;
        readonly useUIStore: UnwrapRef<typeof import("./src/stores/useUIStore")["useUIStore"]>;
        readonly watch: UnwrapRef<typeof import("vue")["watch"]>;
        readonly watchEffect: UnwrapRef<typeof import("vue")["watchEffect"]>;
        readonly watchPostEffect: UnwrapRef<typeof import("vue")["watchPostEffect"]>;
        readonly watchSyncEffect: UnwrapRef<typeof import("vue")["watchSyncEffect"]>;
    }
}
